### ISSUE TITLE
i have  aproblem on my epic cash desktop wallet, i send 277 epic from my phone wallet, that was confirmed on desktop wallet , but it remains unconfirmed when i click the coins button, also tried to refresh balance button but it doesnt scan the blockchain

### ISSUE THREAD

**Issue by RFJ68** [EpicCash/epic#102]
i have  aproblem on my epic cash desktop wallet, i send 277 epic from my phone wallet, that was confirmed on desktop wallet , but it remains unconfirmed when i click the coins button, also tried to refresh balance button but it doesnt scan the blockchain, does anyone know how to solve this problem. i ve send small amount after this transaction and the worked?
Rene

**Comment by actsovereign** [comment]
Rene, I suggest you ask here as this is an Epic Pay wallet issue: https://t.me/EpicCashMobileWallet

**Comment by RFJ68** [comment]
i ve went to telegram but i still haven t got a solution, can i return the epic cash 277 back to my phone wallet? or when it s stuck on the blockchain ( blockchain height 2073444 on my epiccash desktop wallet for this 277 epic transfer ) ?
i ve also run recheck balance scan on desktop wallet but it never comes to a 100% check? is that normal? ive chanced the node setting, recovered wallet etc etc nothing gets my epic back yet??

**Comment by who-biz** [comment]
This is a question for support channels, or GUI repo (https://github.com/EpicCash/epic-gui-wallet) if its a Desktop wallet issue. If it is mobile causing the problem, then @actsovereign is correct that you should go through Mobile Wallet channels.

 But, you should have an option in-wallet to cancel transaction (assuming GUI supports this - I only use CLI)

In any case, this is the repository for Epic's core node software.  It is not the right place for general support inquiries.
