### ISSUE TITLE
ncurses TUI problem

### ISSUE THREAD

**Issue by abrunenko** [EpicCash/epic#119]
**Describe the bug**
My problem is that I can't achieve a normal TUI display in my terminal.

**To Reproduce**
hm..

**Expected behavior**
I would like to see a beautiful interface

**Required data**
 - Node/Wallet/Miner log as text or screenshot
 - Config toml file or command line 
 - OS: Ubuntu 23.10
 - Rust Version : 1.66.0
 - Cargo Version : 1.66.0

**Additional context**
Maybe I'm posting this question to the wrong address. But I can't find a solution(
I'm using a standard gnome terminal application and also guake - in both there is this problem with the display

![image](https://github.com/EpicCash/epic/assets/151728750/c7e424b0-a082-478c-9cb7-6a77d41e34a7)

**Comment by who-biz** [comment]
You need to enable a unicode-compatible locale in your terminal. 

i.e. `en_US.UTF-8` etc. Please search on google for how to do this.

**Comment by who-biz** [comment]
Something like this: https://beebom.com/how-enable-utf-8-support-linux/
