### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by giisystems** [EpicCash/epic#20]
Hello, I have downloaded Linux binaries from the official page and   am trying to run epic server on Ubuntu 20.04.2 LTS.
Followed all the instructions and then run in  the terminal , it crashed:
epic
Performing chain data rollback
Downloading canonical chain data to rollback to
Please wait: this may take a while
Extracting new chain data
Done
Illegal instruction (core dumped)

Any ideas what went wrong?
Hardware is Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz with 8G memory

**Comment by SteveD41** [comment]
I have hit the same problem it appears to be happening in leaf_set.rs on the "Bitmap::create()" line. 

I cannot dig any further as my knowledge of rust is zero and from what I can tell this call is to an external library so there is no real source code I can dig into.

impl LeafSet {
	/// Open the remove log file.
	/// The content of the file will be read in memory for fast checking.
	pub fn open<P: AsRef<Path>>(path: P) -> io::Result<LeafSet> {
		let file_path = path.as_ref();
		let bitmap = if file_path.exists() {
			read_bitmap(&file_path)?
		} else {
			Bitmap::create()
		};

		if !bitmap.is_empty() {
			debug!(
				"bitmap {} pos ({} bytes)",
				bitmap.cardinality(),
				bitmap.get_serialized_size_in_bytes(),
			);
		}

		Ok(LeafSet {
			path: file_path.to_path_buf(),
			bitmap_bak: bitmap.clone(),
			bitmap,
		})
	}

**Comment by who-biz** [comment]
Please let me know if this is still happening for unknown reasons.

Closing due to 2+ yr issue age, and suspected resolution
