### ISSUE TITLE
Default peers settings are crashing synchronization

### ISSUE THREAD

**Issue by blacktyger** [EpicCash/epic#24]
With epic-server.toml default settings server is not synchronizing after downloading the 'rollback canonical chain data' . Users have manually changed `peers_preferred` and `peers_deny` in order to start synchronize with live chain.

**Comment by JualnSilva** [comment]
We have two engineers that synchronized with the chain on mainnet without having to change these two fields mentioned.

They just run the server and wait until the chain has the head with the most current value.

**Can you provide more details about the problem?** So we can check if it really is something to change the file generation pattern or if they are special cases

**Comment by who-biz** [comment]
If this still occurs, please comment and provide more details.

Marked wontfix, closing.
