### ISSUE TITLE
Server Install Instructions Wrong

### ISSUE THREAD

**Issue by skykingisepic** [EpicCash/epic#71]
There is no .deb file in the downloaded .zip file from epic.tech

Should say: unzip file, change execute perms for epic (chmod +x epic) and run ./epic

**Comment by Jualns** [comment]
We are releasing a new version of Epic Server and Epic Wallet. We'll put new binaries with the fix for this execute permission issue.

This will happen in a few days, as soon as we start the testing process, which is supposed to last 15 days, we'll put the new binaries in the epic.tech

**Comment by jhelison** [comment]
Now we are following the steps on the new Epic Cash wiki: 
- [Running the server](https://github.com/EpicCash/documentation/wiki/Running-the-server)
- [Running the wallet](https://github.com/EpicCash/documentation/wiki/Running-the-wallet)

Closing this issue.
